/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as IndustriesIndustryRouteImport } from './routes/industries.$industry'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as ApiPublicSetupCronOnceRouteImport } from './routes/api/public/setup-cron-once'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known.mcp.server-card[.]json'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicOgSlugRouteImport } from './routes/api/public/og/$slug'
import { Route as ApiPublicHooksGenerateDailyDraftRouteImport } from './routes/api/public/hooks/generate-daily-draft'
import { Route as ApiPublicHooksAutoPublishStaleRouteImport } from './routes/api/public/hooks/auto-publish-stale'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndustryRoute = IndustriesIndustryRouteImport.update({
  id: '/industries/$industry',
  path: '/industries/$industry',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupCronOnceRoute = ApiPublicSetupCronOnceRouteImport.update({
  id: '/api/public/setup-cron-once',
  path: '/api/public/setup-cron-once',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/admin/blog/',
    path: '/admin/blog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOgSlugRoute = ApiPublicOgSlugRouteImport.update({
  id: '/api/public/og/$slug',
  path: '/api/public/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateDailyDraftRoute =
  ApiPublicHooksGenerateDailyDraftRouteImport.update({
    id: '/api/public/hooks/generate-daily-draft',
    path: '/api/public/hooks/generate-daily-draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoPublishStaleRoute =
  ApiPublicHooksAutoPublishStaleRouteImport.update({
    id: '/api/public/hooks/auto-publish-stale',
    path: '/api/public/hooks/auto-publish-stale',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/admin/blog/$id',
    path: '/admin/blog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth.md': typeof AuthDotmdRoute
  '/contact': typeof ContactRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/setup-cron-once': typeof ApiPublicSetupCronOnceRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/api/public/hooks/auto-publish-stale': typeof ApiPublicHooksAutoPublishStaleRoute
  '/api/public/hooks/generate-daily-draft': typeof ApiPublicHooksGenerateDailyDraftRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth.md': typeof AuthDotmdRoute
  '/contact': typeof ContactRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/setup-cron-once': typeof ApiPublicSetupCronOnceRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/api/public/hooks/auto-publish-stale': typeof ApiPublicHooksAutoPublishStaleRoute
  '/api/public/hooks/generate-daily-draft': typeof ApiPublicHooksGenerateDailyDraftRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth.md': typeof AuthDotmdRoute
  '/contact': typeof ContactRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/setup-cron-once': typeof ApiPublicSetupCronOnceRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/api/public/hooks/auto-publish-stale': typeof ApiPublicHooksAutoPublishStaleRoute
  '/api/public/hooks/generate-daily-draft': typeof ApiPublicHooksGenerateDailyDraftRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/auth.md'
    | '/contact'
    | '/feed.xml'
    | '/services'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/industries/$industry'
    | '/locations/$city'
    | '/blog/'
    | '/industries/'
    | '/locations/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/setup-cron-once'
    | '/admin/blog/$id'
    | '/api/public/hooks/auto-publish-stale'
    | '/api/public/hooks/generate-daily-draft'
    | '/api/public/og/$slug'
    | '/lovable/email/queue/process'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/auth.md'
    | '/contact'
    | '/feed.xml'
    | '/services'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/industries/$industry'
    | '/locations/$city'
    | '/blog'
    | '/industries'
    | '/locations'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/setup-cron-once'
    | '/admin/blog/$id'
    | '/api/public/hooks/auto-publish-stale'
    | '/api/public/hooks/generate-daily-draft'
    | '/api/public/og/$slug'
    | '/lovable/email/queue/process'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/auth.md'
    | '/contact'
    | '/feed.xml'
    | '/services'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/industries/$industry'
    | '/locations/$city'
    | '/blog/'
    | '/industries/'
    | '/locations/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/setup-cron-once'
    | '/_authenticated/admin/blog/$id'
    | '/api/public/hooks/auto-publish-stale'
    | '/api/public/hooks/generate-daily-draft'
    | '/api/public/og/$slug'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthDotmdRoute: typeof AuthDotmdRoute
  ContactRoute: typeof ContactRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesIndustryRoute: typeof IndustriesIndustryRoute
  LocationsCityRoute: typeof LocationsCityRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiPublicSetupCronOnceRoute: typeof ApiPublicSetupCronOnceRoute
  ApiPublicHooksAutoPublishStaleRoute: typeof ApiPublicHooksAutoPublishStaleRoute
  ApiPublicHooksGenerateDailyDraftRoute: typeof ApiPublicHooksGenerateDailyDraftRoute
  ApiPublicOgSlugRoute: typeof ApiPublicOgSlugRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$industry': {
      id: '/industries/$industry'
      path: '/industries/$industry'
      fullPath: '/industries/$industry'
      preLoaderRoute: typeof IndustriesIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-cron-once': {
      id: '/api/public/setup-cron-once'
      path: '/api/public/setup-cron-once'
      fullPath: '/api/public/setup-cron-once'
      preLoaderRoute: typeof ApiPublicSetupCronOnceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$slug': {
      id: '/api/public/og/$slug'
      path: '/api/public/og/$slug'
      fullPath: '/api/public/og/$slug'
      preLoaderRoute: typeof ApiPublicOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-daily-draft': {
      id: '/api/public/hooks/generate-daily-draft'
      path: '/api/public/hooks/generate-daily-draft'
      fullPath: '/api/public/hooks/generate-daily-draft'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-publish-stale': {
      id: '/api/public/hooks/auto-publish-stale'
      path: '/api/public/hooks/auto-publish-stale'
      fullPath: '/api/public/hooks/auto-publish-stale'
      preLoaderRoute: typeof ApiPublicHooksAutoPublishStaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthDotmdRoute: AuthDotmdRoute,
  ContactRoute: ContactRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesIndustryRoute: IndustriesIndustryRoute,
  LocationsCityRoute: LocationsCityRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiPublicSetupCronOnceRoute: ApiPublicSetupCronOnceRoute,
  ApiPublicHooksAutoPublishStaleRoute: ApiPublicHooksAutoPublishStaleRoute,
  ApiPublicHooksGenerateDailyDraftRoute: ApiPublicHooksGenerateDailyDraftRoute,
  ApiPublicOgSlugRoute: ApiPublicOgSlugRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
